# input file are generated by
# cat LEP_ZYG_ATGCA_WITHcloset_SNP.bed | awk '{print $11}' | LC_ALL=C sort -n| uniq -c >  Counts_number.txt


from sys import argv
input_fp = argv[1]
if len(argv) == 3:
    upto = int(argv[2])
else:
    upto = 200



sum_of_count = 0
number = 0
with open(input_fp) as f:
    while int(number) <upto:
        count, number = f.readline().strip().split()
        sum_of_count += int(count)
        print number+'\t'+str(sum_of_count)


